# Generated by Django 4.1.7 on 2023-03-13 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinycharacters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('enemy_type', models.CharField(max_length=200)),
                ('min_level', models.IntegerField()),
                ('nr_public_events', models.IntegerField()),
                ('nr_lost_sectors', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=200)),
                ('weapon_slot', models.CharField(max_length=200)),
                ('weapon_element', models.CharField(max_length=200)),
                ('weapon_type', models.CharField(max_length=200)),
                ('weapon_damage', models.IntegerField()),
                ('player_weapon', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='destinycharacters.player')),
            ],
        ),
    ]
