# Generated by Django 4.1.7 on 2023-03-18 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinycharacters', '0002_location_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_rate', models.IntegerField()),
                ('loc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='destinycharacters.location')),
                ('wep', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='destinycharacters.weapon')),
            ],
        ),
    ]
