# Generated by Django 4.1.7 on 2023-03-19 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinycharacters', '0003_location_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='all_weapons',
            field=models.ManyToManyField(through='destinycharacters.Location_Weapon', to='destinycharacters.weapon'),
        ),
        migrations.AlterField(
            model_name='location_weapon',
            name='loc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='destinycharacters.location'),
        ),
        migrations.AlterField(
            model_name='location_weapon',
            name='wep',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='destinycharacters.weapon'),
        ),
    ]
