# Generated by Django 4.1.7 on 2023-03-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinycharacters', '0004_location_all_weapons_alter_location_weapon_loc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='class1',
            field=models.CharField(choices=[('H', 'Hunter'), ('T', 'Titan'), ('W', 'Warlock')], default='H', max_length=200),
        ),
    ]
