# Generated by Django 4.1.7 on 2023-03-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinycharacters', '0005_alter_player_class1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='class1',
            field=models.CharField(choices=[('Hunter', 'Hunter'), ('Titan', 'Titan'), ('Warlock', 'Warlock')], default='Hunter', max_length=200),
        ),
    ]
