# Generated by Django 4.1.7 on 2023-03-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinycharacters', '0006_alter_player_class1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='weapon_element',
            field=models.CharField(choices=[('Void', 'Void'), ('Solar', 'Solar'), ('Arc', 'Arc'), ('Stasis', 'Stasis'), ('Strand', 'Strand'), ('Kinetic', 'Kinetic')], default='Void', max_length=200),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_slot',
            field=models.CharField(choices=[('Kinetic', 'Kinetic'), ('Energy', 'Energy'), ('Heavy', 'Heavy')], default='Kinetic', max_length=200),
        ),
    ]
